### ISSUE TITLE
Can't read Yaml OpenAPI specification

### ISSUE THREAD

**Issue by pies** [apioo/psx-api#7]
I can't figure out a way to read OpenAPI or Swagger from an Yaml file, as they are usually presented.

It's certainly possible since I can easily implement a version of PSX\Api\Parser\OpenAPI that does that by switching the Json parser to a Yaml parser, but I was wondering if it's somehow possible out of the box.

**Comment by chriskapp** [comment]
Hi, this is currently not possible since the parser only understands json but I think this would be a great feature. In the `OpenAPI::fromFile` method we could check the file extension and use the symfony yaml parser to convert the yaml to json.

**Comment by chriskapp** [comment]
I will close this issue since it looks there is nothing more todo here.

**Comment by xvilo** [comment]
@chriskapp I was wondering, is this already implemented, or did you change your mind? It seems it's still needing JSON based on what I see
